/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[value]/case1': RouteRecordInfo<
      '/[value]/case1',
      '/:value/case1',
      { value: ParamValue<true> },
      { value: ParamValue<false> },
      | never
    >,
    '/[value]/case2': RouteRecordInfo<
      '/[value]/case2',
      '/:value/case2',
      { value: ParamValue<true> },
      { value: ParamValue<false> },
      | never
    >,
    '/[value]/case3': RouteRecordInfo<
      '/[value]/case3',
      '/:value/case3',
      { value: ParamValue<true> },
      { value: ParamValue<false> },
      | never
    >,
    '/[value]/case4': RouteRecordInfo<
      '/[value]/case4',
      '/:value/case4',
      { value: ParamValue<true> },
      { value: ParamValue<false> },
      | never
    >,
    '/casex': RouteRecordInfo<
      '/casex',
      '/casex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/casey': RouteRecordInfo<
      '/casey',
      '/casey',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[value]/case1.vue': {
      routes:
        | '/[value]/case1'
      views:
        | never
    }
    'src/pages/[value]/case2.vue': {
      routes:
        | '/[value]/case2'
      views:
        | never
    }
    'src/pages/[value]/case3.vue': {
      routes:
        | '/[value]/case3'
      views:
        | never
    }
    'src/pages/[value]/case4.vue': {
      routes:
        | '/[value]/case4'
      views:
        | never
    }
    'src/pages/casex.vue': {
      routes:
        | '/casex'
      views:
        | never
    }
    'src/pages/casey.vue': {
      routes:
        | '/casey'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
